### ISSUE TITLE
Remove shell-escape dependency

### ISSUE THREAD

**Issue by matthiasbeyer** [sharkdp/bugreport#14]
Maybe we should remove the `shell-dependency` dependency: https://web.crev.dev/rust-reviews/crate/shell-escape/0.1.5/N/

**Comment by sharkdp** [comment]
What exactly should I look at on the linked website?

**Comment by matthiasbeyer** [comment]
About the crate review. Also, the crate has not been maintained since a few years already.

**Comment by sharkdp** [comment]
Ok, and what would be the replacement?

**Comment by matthiasbeyer** [comment]
Yeah that is actually an issue... a quick search on crates did not provide anything useful :disappointed:

**Comment by unlimitedsola** [comment]
[`shell-escape`](https://github.com/sfackler/shell-escape) only [contains ~100 lines of code](https://github.com/sfackler/shell-escape/blob/9bfec037f6fde99a7e4caf029919b0bb4b808c85/src/lib.rs) with no dependency whatsoever. I don't think we need to worry about it not being maintained if there isn't something broken. In the future, if we run into any issues with this crate we can easily pull the code into the project and maintain it ourselves.
