### ISSUE TITLE
Use vergen to provide compile-time version information

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bugreport#2]
.. like a Gith SHA1 Hash

https://crates.io/crates/vergen

**Comment by extrawurst** [comment]
@sharkdp why did you end up not going with it? I currently struggle with `bugreport` using `git-version` which seems highly unmaintained and not moving forward to use `syn2`: https://github.com/fusion-engineering/rust-git-version/pull/20

**Comment by sharkdp** [comment]
I think I closed this after https://github.com/sharkdp/bugreport/pull/6 by @Enselic was merged.

@extrawurst Do you know if vergen can cover all of our use-cases?

**Comment by Enselic** [comment]
For the record: if there is a better way to get git hash info now, feel very free to rip out my code and replace it with something better!
