### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by Lynnesbian** [sharkdp/bugreport#7]
I hate to be the bearer of bad news, but...

One of `bugreport`'s dependencies, [`snailquote`](https://crates.io/crates/snailquote), is [GPLv3 licensed](https://github.com/euank/snailquote/blob/master/LICENSE). The GPL (as opposed to e.g. the LGPL), requires that [any code linking to it](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL) must also be GPL (which `bugreport` is not).

**Comment by sharkdp** [comment]
Thank you for reporting this! This is an oversight on my part and should definitely be fixed (by replacing snailquote). It might take me a few days before I get to it.

(I wish crates.io would have a mechanism to warn of scenarios like that)

**Comment by sharkdp** [comment]
Resolved by using the `shell-escape` crate. It's not a drop-in replacement, unfortunately. I liked the snailquote escaping better for some inputs. Anyways.. this is more of a "cosmetic" issue.
